### ISSUE TITLE
Meta dreifingar

### ISSUE THREAD

**Issue by tungufoss** [HI-IDN/IDN403M-Hermun-2024#5]
- [ ] Skoða gögnin myndrænt
- [ ] Sía út útlaga 
- [ ] Velja dreifingu/r fyrir millikomutíma og vinnslutíma
